apiVersion: v1
kind: Template
labels:
  template: cakephp-example
metadata:
  annotations:
    description: An example CakePHP application with no database
    iconClass: icon-php
    tags: instant-app,php,cakephp
  creationTimestamp: null
  name: cakephp-example
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Exposes and load balances the application pods
    name: cakephp-example
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: cakephp-example
- apiVersion: v1
  kind: Route
  metadata:
    name: cakephp-example
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: cakephp-example
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: cakephp-example
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: cakephp-example
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cakephp-example:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: php:5.6
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
    name: cakephp-example
  spec:
    replicas: 1
    selector:
      name: cakephp-example
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: cakephp-example
        name: cakephp-example
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: ${DATABASE_SERVICE_NAME}
          - name: DATABASE_ENGINE
            value: ${DATABASE_ENGINE}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_USER
            value: ${DATABASE_USER}
          - name: DATABASE_PASSWORD
            value: ${DATABASE_PASSWORD}
          - name: CAKEPHP_SECRET_TOKEN
            value: ${CAKEPHP_SECRET_TOKEN}
          - name: CAKEPHP_SECURITY_SALT
            value: ${CAKEPHP_SECURITY_SALT}
          - name: CAKEPHP_SECURITY_CIPHER_SEED
            value: ${CAKEPHP_SECURITY_CIPHER_SEED}
          - name: OPCACHE_REVALIDATE_FREQ
            value: ${OPCACHE_REVALIDATE_FREQ}
          image: cakephp-example
          name: cakephp-example
          ports:
          - containerPort: 8080
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cakephp-example
        from:
          kind: ImageStreamTag
          name: cakephp-example:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The URL of the repository with your application source code
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/openshift/cakephp-ex.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch
  name: SOURCE_REPOSITORY_REF
- description: Set this to the relative path to your project if it is not in the root
    of your repository
  name: CONTEXT_DIR
- description: The exposed hostname that will route to the CakePHP service, if left
    blank a value will be defaulted.
  name: APPLICATION_DOMAIN
- description: A secret string used to configure the GitHub webhook
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: GITHUB_WEBHOOK_SECRET
- description: Database service name
  name: DATABASE_SERVICE_NAME
- description: 'Database engine: postgresql, mysql or sqlite (default)'
  name: DATABASE_ENGINE
- description: Database name
  name: DATABASE_NAME
- description: Database user name
  name: DATABASE_USER
- description: Database user password
  name: DATABASE_PASSWORD
- description: Set this to a long random string
  from: '[\w]{50}'
  generate: expression
  name: CAKEPHP_SECRET_TOKEN
- description: Security salt for session hash
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: CAKEPHP_SECURITY_SALT
- description: Security cipher seed for session hash
  from: '[0-9]{30}'
  generate: expression
  name: CAKEPHP_SECURITY_CIPHER_SEED
- description: The How often to check script timestamps for updates, in seconds. 0
    will result in OPcache checking for updates on every request.
  name: OPCACHE_REVALIDATE_FREQ
  value: "2"
